### PR TITLE
Improvements to pkgdown site

### LINKED ISSUE #128: Improvements to pkgdown site
- don't document some internal fxns (with `#' @noRd`)
- organized references in `_pkgdown.yml` (see [PR#44](https://github.com/bcgov/bcmaps/pull/44/commits/931b2dc7994e6735f3f7721eaf909308f9755c43))
- use auto detect development mode in `_pkgdown.yml`

```
development:
     mode: auto
```

- bring in anything else nice from PR #44

### PR DESCRIPTION
**Pull request by ateucher**
In preparation for release. Closes #128:

- [x] don't document some internal fxns (with `#' @noRd`)
- [x] organized references in `_pkgdown.yml` (see [PR#44](https://github.com/bcgov/bcmaps/pull/44/commits/931b2dc7994e6735f3f7721eaf909308f9755c43))
- [x] use auto detect development mode in `_pkgdown.yml`

### CODE REVIEW

**Comment by ateucher** [comment]
I'm not worried about the failure in the HTML-5 check... and we'll need to merge to actually see the dev pkgdown site - unless you want to render locally

**Review by boshek — APPROVED** [review]
Oh this is nice! Great breakup of functionality. 

Question - do we even need that HTML-5 check anymore?

**Comment by ateucher** [comment]
> Question - do we even need that HTML-5 check anymore?

Yeah, probably not. I don't really remember what it's for...

**Comment by boshek** [comment]
> > Question - do we even need that HTML-5 check anymore?
> 
> 
> 
> Yeah, probably not. I don't really remember what it's for...

It was a dedicated check for CRAN. I think we can safely remove it honestly.

**Comment by stephhazlitt** [comment]
I don't have band width to review properly so just giving a 👍 with this working and look lovely on your laptops.

**Review by stephhazlitt — APPROVED** [review]

**Pull request merged**
