### PR TITLE
Show files

### PR DESCRIPTION
**Pull request by ateucher**
Adds more information to `show_cached_files()` so a user can know how much space they are taking up. #92

### CODE REVIEW

**Comment by boshek** [comment]
Looks great. Did we want to go through the trouble of compute the size of subfolders? Right now it just the `cded` but in the output of `show_cached_files` the CDED directory has a size zero.

**Comment by ateucher** [comment]
I wondered about that too... or an argument (or other function) to show the cded cache?

**Comment by boshek** [comment]
Feels like it belong in the show files function somehow especially since it is likely to be by far the biggest thing taking up space. I guess you could have `show_cded_cached_files` and then have `show_cached_files` call that?

**Comment by ateucher** [comment]
I guess just expanding the cded folder would be the simplest... with a cded (logical) argument whether or not you want to show it?

**Comment by boshek** [comment]
I think that might end up being less useful as 95% of the files are cded files. I wonder if we could summarise it by the directors _or_ files at this location: `bcmaps:::data_dir()`? So in this case cded is just the sum of file sizes of a recursive list of what in cded.

**Comment by ateucher** [comment]
Yeah that's good

**Review by boshek — APPROVED** [review]

**Pull request merged**
